/*------------------------
 SEQUENCIAL 10 LEDS - Ricardo Almeida
 ricardo.ams@live.com - https://www.facebook.com/RicardoAlmeidaMelo
 CRIADO: 09/12/2015 - ATUALIZADO: 13-01-2016
 ------------------------*/
int led0 = 2;
int led1 = 3;
int led2 = 4;
int led3 = 5;
int led4 = 6;
int led5 = 7;
int led6 = 8;
int led7 = 9;
int led8 = 10;
int led9 = 11;

void setup() {

pinMode(led0, OUTPUT);
pinMode(led1, OUTPUT);
pinMode(led2, OUTPUT);
pinMode(led3, OUTPUT);
pinMode(led4, OUTPUT);
pinMode(led5, OUTPUT);
pinMode(led6, OUTPUT);
pinMode(led7, OUTPUT);
pinMode(led8, OUTPUT);
pinMode(led9, OUTPUT);
}
void loop() {

// EFEITO 1 - Vai e Volta - ********************************
for(int i = 0; i < 4; i++){
digitalWrite(led0, HIGH);
delay(100);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(100);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(100);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(100);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(100);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(100);
digitalWrite(led5, LOW);
digitalWrite(led6, HIGH);
delay(100);
digitalWrite(led6, LOW);
digitalWrite(led7, HIGH);
delay(100);
digitalWrite(led7, LOW);
digitalWrite(led8, HIGH);
delay(100);
digitalWrite(led8, LOW);
digitalWrite(led9, HIGH);
delay(100);
digitalWrite(led9, LOW);
digitalWrite(led8, HIGH);
delay(100);
digitalWrite(led8, LOW);
digitalWrite(led7, HIGH);
delay(100);
digitalWrite(led7, LOW);
digitalWrite(led6, HIGH);
delay(100);
digitalWrite(led6, LOW);
digitalWrite(led5, HIGH);
delay(100);
digitalWrite(led5, LOW);
digitalWrite(led4, HIGH);
delay(100);
digitalWrite(led4, LOW);
digitalWrite(led3, HIGH);
delay(100);
digitalWrite(led3, LOW);
digitalWrite(led2, HIGH);
delay(100);
digitalWrite(led2, LOW);
digitalWrite(led1, HIGH);
delay(100);
digitalWrite(led1, LOW);
}

// EFEITO 2 Girando********************************
for(int i = 0; i < 27; i++){
digitalWrite(led0, HIGH);
delay(35);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(35);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(35);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(35);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(35);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(35);
digitalWrite(led5, LOW);
digitalWrite(led6, HIGH);
delay(35);
digitalWrite(led6, LOW);
digitalWrite(led7, HIGH);
delay(35);
digitalWrite(led7, LOW);
digitalWrite(led8, HIGH);
delay(35);
digitalWrite(led8, LOW);
digitalWrite(led9, HIGH);
delay(35);
digitalWrite(led9, LOW);
}

// EFEITO 3 - Pisca Ímpar, Par ********************************
for(int i = 0; i < 15; i++){
digitalWrite(led0, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led1, LOW);
digitalWrite(led3, LOW);
digitalWrite(led5, LOW);
digitalWrite(led7, LOW);
digitalWrite(led9, LOW);
delay(200);
digitalWrite(led0, LOW);
digitalWrite(led2, LOW);
digitalWrite(led4, LOW);
digitalWrite(led6, LOW);
digitalWrite(led8, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led9, HIGH);
delay(200);
}
digitalWrite(led1, LOW);
digitalWrite(led3, LOW);
digitalWrite(led5, LOW);
digitalWrite(led7, LOW);
digitalWrite(led9, LOW);
delay(100);

// EFEITO 4 - Vu Meter********************************
for(int i = 0; i < 4; i++){
digitalWrite(led0, HIGH);
delay(100);
digitalWrite(led1, HIGH);
delay(100);
digitalWrite(led2, HIGH);
delay(100);
digitalWrite(led3, HIGH);
delay(100);
digitalWrite(led4, HIGH);
delay(100);
digitalWrite(led5, HIGH);
delay(100);
digitalWrite(led6, HIGH);
delay(100);
digitalWrite(led7, HIGH);
delay(100);
digitalWrite(led8, HIGH);
delay(100);
digitalWrite(led9, HIGH);
delay(100);
digitalWrite(led9, LOW);
delay(100);
digitalWrite(led8, LOW);
delay(100);
digitalWrite(led7, LOW);
delay(100);
digitalWrite(led6, LOW);
delay(100);
digitalWrite(led5, LOW);
delay(100);
digitalWrite(led4, LOW);
delay(100);
digitalWrite(led3, LOW);
delay(100);
digitalWrite(led2, LOW);
delay(100);
digitalWrite(led1, LOW);
delay(100);
digitalWrite(led0, LOW);
delay(200);
}

// EFEITO 5 - Policia 1 - ********************************
for(int i = 0; i < 7; i++){
for(int i = 0; i < 6; i++){
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(60);
digitalWrite(led5, LOW);
digitalWrite(led6, LOW);
digitalWrite(led7, LOW);
digitalWrite(led8, LOW);
digitalWrite(led9, LOW);
delay(60);
}
for(int i = 0; i < 6; i++){
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
delay(60);
digitalWrite(led0, LOW);
digitalWrite(led1, LOW);
digitalWrite(led2, LOW);
digitalWrite(led3, LOW);
digitalWrite(led4, LOW);
delay(60);
}
}

// EFEITO 6 - Giroflex - ********************************
for(int i = 0; i < 30; i++){
digitalWrite(led0, HIGH);
digitalWrite(led5, HIGH);
delay(50);
digitalWrite(led0, LOW);
digitalWrite(led5, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led6, HIGH);
delay(50);
digitalWrite(led1, LOW);
digitalWrite(led6, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(50);
digitalWrite(led2, LOW);
digitalWrite(led7, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led8, HIGH);
delay(50);
digitalWrite(led3, LOW);
digitalWrite(led8, LOW);
digitalWrite(led4, HIGH);
digitalWrite(led9, HIGH);
delay(50);
digitalWrite(led4, LOW);
digitalWrite(led9, LOW);
}

// EFEITO 7 - Policia 2 - ********************************
for(int i = 0; i < 8; i++){
for(int i = 0; i < 6; i++){
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(55);
digitalWrite(led0, LOW);
digitalWrite(led1, LOW);
digitalWrite(led2, LOW);
digitalWrite(led3, LOW);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led6, LOW);
digitalWrite(led7, LOW);
digitalWrite(led8, LOW);
digitalWrite(led9, LOW);
delay(55);
}
delay(300);
}

// EFEITO 8 - Zig-Zag ********************************
for(int i = 0; i < 7; i++){
digitalWrite(led0, HIGH);
delay(90);
digitalWrite(led0, LOW);
digitalWrite(led2, HIGH);
delay(90);
digitalWrite(led2, LOW);
digitalWrite(led1, HIGH);
delay(90);
digitalWrite(led1, LOW);
digitalWrite(led3, HIGH);
delay(90);
digitalWrite(led3, LOW);
digitalWrite(led2, HIGH);
delay(90);
digitalWrite(led2, LOW);
digitalWrite(led4, HIGH);
delay(90);
digitalWrite(led4, LOW);
digitalWrite(led3, HIGH);
delay(90);
digitalWrite(led3, LOW);
digitalWrite(led5, HIGH);
delay(90);
digitalWrite(led5, LOW);
digitalWrite(led4, HIGH);
delay(90);
digitalWrite(led4, LOW);
digitalWrite(led6, HIGH);
delay(90);
digitalWrite(led6, LOW);
digitalWrite(led5, HIGH);
delay(90);
digitalWrite(led5, LOW);
digitalWrite(led7, HIGH);
delay(90);
digitalWrite(led7, LOW);
digitalWrite(led6, HIGH);
delay(90);
digitalWrite(led6, LOW);
digitalWrite(led8, HIGH);
delay(90);
digitalWrite(led8, LOW);
digitalWrite(led7, HIGH);
delay(90);
digitalWrite(led7, LOW);
digitalWrite(led9, HIGH);
delay(90);
digitalWrite(led9, LOW);
digitalWrite(led8, HIGH);
delay(90);
digitalWrite(led8, LOW);
digitalWrite(led0, HIGH);
delay(90);
digitalWrite(led0, LOW);
digitalWrite(led9, HIGH);
delay(90);
digitalWrite(led9, LOW);
digitalWrite(led1, HIGH);
delay(90);
digitalWrite(led1, LOW);
}

// EFEITO 9 - Soma 1 ********************************
for(int i = 0; i < 3; i++){
// Indo
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(95);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(95);
digitalWrite(led5, LOW);
digitalWrite(led6, HIGH);
delay(95);
digitalWrite(led6, LOW);
digitalWrite(led7, HIGH);
delay(95);
digitalWrite(led7, LOW);
digitalWrite(led8, HIGH);
delay(95);
digitalWrite(led8, LOW);
digitalWrite(led9, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(95);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(95);
digitalWrite(led5, LOW);
digitalWrite(led6, HIGH);
delay(95);
digitalWrite(led6, LOW);
digitalWrite(led7, HIGH);
delay(95);
digitalWrite(led7, LOW);
digitalWrite(led8, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(95);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(95);
digitalWrite(led5, LOW);
digitalWrite(led6, HIGH);
delay(95);
digitalWrite(led6, LOW);
digitalWrite(led7, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(95);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(95);
digitalWrite(led5, LOW);
digitalWrite(led6, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(95);
digitalWrite(led4, LOW);
digitalWrite(led5, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led3, LOW);
digitalWrite(led4, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led2, LOW);
digitalWrite(led3, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
digitalWrite(led0, LOW);
digitalWrite(led1, HIGH);
delay(95);
digitalWrite(led0, HIGH);
delay(95);
// Apagando
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led6, HIGH);
digitalWrite(led5, LOW);
delay(70);
digitalWrite(led5, HIGH);
digitalWrite(led4, LOW);
delay(70);
digitalWrite(led4, HIGH);
digitalWrite(led3, LOW);
delay(70);
digitalWrite(led3, HIGH);
digitalWrite(led2, LOW);
delay(70);
digitalWrite(led2, HIGH);
digitalWrite(led1, LOW);
delay(70);
digitalWrite(led1, HIGH);
digitalWrite(led0, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led6, HIGH);
digitalWrite(led5, LOW);
delay(70);
digitalWrite(led5, HIGH);
digitalWrite(led4, LOW);
delay(70);
digitalWrite(led4, HIGH);
digitalWrite(led3, LOW);
delay(70);
digitalWrite(led3, HIGH);
digitalWrite(led2, LOW);
delay(70);
digitalWrite(led2, HIGH);
digitalWrite(led1, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led6, HIGH);
digitalWrite(led5, LOW);
delay(70);
digitalWrite(led5, HIGH);
digitalWrite(led4, LOW);
delay(70);
digitalWrite(led4, HIGH);
digitalWrite(led3, LOW);
delay(70);
digitalWrite(led3, HIGH);
digitalWrite(led2, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led6, HIGH);
digitalWrite(led5, LOW);
delay(70);
digitalWrite(led5, HIGH);
digitalWrite(led4, LOW);
delay(70);
digitalWrite(led4, HIGH);
digitalWrite(led3, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led6, HIGH);
digitalWrite(led5, LOW);
delay(70);
digitalWrite(led5, HIGH);
digitalWrite(led4, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led6, HIGH);
digitalWrite(led5, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led7, HIGH);
digitalWrite(led6, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led8, HIGH);
digitalWrite(led7, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(70);
digitalWrite(led9, HIGH);
digitalWrite(led8, LOW);
delay(70);
digitalWrite(led9, LOW);
delay(100);
}

// EFEITO 10 - Passando direto ********************************
for(int i = 0; i < 3; i++){
digitalWrite(led0, HIGH);
delay(100);
digitalWrite(led1, HIGH);
delay(100);
digitalWrite(led2, HIGH);
delay(100);
digitalWrite(led3, HIGH);
delay(100);
digitalWrite(led4, HIGH);
delay(100);
digitalWrite(led5, HIGH);
delay(100);
digitalWrite(led6, HIGH);
delay(100);
digitalWrite(led7, HIGH);
delay(100);
digitalWrite(led8, HIGH);
delay(100);
digitalWrite(led9, HIGH);
delay(100);

digitalWrite(led0, LOW);
delay(100);
digitalWrite(led1, LOW);
delay(100);
digitalWrite(led2, LOW);
delay(100);
digitalWrite(led3, LOW);
delay(100);
digitalWrite(led4, LOW);
delay(100);
digitalWrite(led5, LOW);
delay(100);
digitalWrite(led6, LOW);
delay(100);
digitalWrite(led7, LOW);
delay(100);
digitalWrite(led8, LOW);
delay(100);
digitalWrite(led9, LOW);
delay(100);

digitalWrite(led9, HIGH);
delay(100);
digitalWrite(led8, HIGH);
delay(100);
digitalWrite(led7, HIGH);
delay(100);
digitalWrite(led6, HIGH);
delay(100);
digitalWrite(led5, HIGH);
delay(100);
digitalWrite(led4, HIGH);
delay(100);
digitalWrite(led3, HIGH);
delay(100);
digitalWrite(led2, HIGH);
delay(100);
digitalWrite(led1, HIGH);
delay(100);
digitalWrite(led0, HIGH);
delay(100);

digitalWrite(led9, LOW);
delay(100);
digitalWrite(led8, LOW);
delay(100);
digitalWrite(led7, LOW);
delay(100);
digitalWrite(led6, LOW);
delay(100);
digitalWrite(led5, LOW);
delay(100);
digitalWrite(led4, LOW);
delay(100);
digitalWrite(led3, LOW);
delay(100);
digitalWrite(led2, LOW);
delay(100);
digitalWrite(led1, LOW);
delay(100);
digitalWrite(led0, LOW);
delay(100);
}

// EFEITO 11 ********************************
for(int i = 0; i < 12; i++){
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(150);
digitalWrite(led0, LOW);
digitalWrite(led2, LOW);
digitalWrite(led4, LOW);
digitalWrite(led6, LOW);
digitalWrite(led8, LOW);
delay(350);
digitalWrite(led0, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led8, HIGH);
delay(150);
digitalWrite(led1, LOW);
digitalWrite(led3, LOW);
digitalWrite(led5, LOW);
digitalWrite(led7, LOW);
digitalWrite(led9, LOW);
delay(350);
}

digitalWrite(led0, LOW);
digitalWrite(led2, LOW);
digitalWrite(led4, LOW);
digitalWrite(led6, LOW);
digitalWrite(led8, LOW);
delay(150);

// EFEITO 12 - Cruzado - ********************************
for(int i = 0; i < 12; i++){
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
delay(91);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
delay(91);
digitalWrite(led3, LOW);
digitalWrite(led6, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(91);
digitalWrite(led2, LOW);
digitalWrite(led7, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led8, HIGH);
delay(91);
digitalWrite(led1, LOW);
digitalWrite(led8, LOW);
digitalWrite(led0, HIGH);
digitalWrite(led9, HIGH);
delay(91);
digitalWrite(led0, LOW);
digitalWrite(led9, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led8, HIGH);
delay(91);
digitalWrite(led1, LOW);
digitalWrite(led8, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(91);
digitalWrite(led2, LOW);
digitalWrite(led7, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
delay(91);
digitalWrite(led3, LOW);
digitalWrite(led6, LOW);
}

// EFEITO 13 - 3 em 3 - ********************************
for(int i = 0; i < 8; i++){
digitalWrite(led7, LOW);
digitalWrite(led0, HIGH);
delay(103);
digitalWrite(led8, LOW);
digitalWrite(led1, HIGH);
delay(103);
digitalWrite(led9, LOW);
digitalWrite(led2, HIGH);
delay(103);
digitalWrite(led0, LOW);
digitalWrite(led3, HIGH);
delay(103);
digitalWrite(led1, LOW);
digitalWrite(led4, HIGH);
delay(103);
digitalWrite(led2, LOW);
digitalWrite(led5, HIGH);
delay(103);
digitalWrite(led3, LOW);
digitalWrite(led6, HIGH);
delay(103);
digitalWrite(led4, LOW);
digitalWrite(led7, HIGH);
delay(103);
digitalWrite(led5, LOW);
digitalWrite(led8, HIGH);
delay(103);
digitalWrite(led6, LOW);
digitalWrite(led9, HIGH);
delay(103);
}
digitalWrite(led7, LOW);
delay(103);
digitalWrite(led8, LOW);
delay(103);
digitalWrite(led9, LOW);

// EFEITO 14 - 4 em 4 ********************************
for(int i = 0; i < 7; i++){
digitalWrite(led0, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led7, HIGH);
delay(100);
digitalWrite(led0, LOW);
digitalWrite(led2, LOW);
digitalWrite(led5, LOW);
digitalWrite(led7, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led8, HIGH);
delay(100);
digitalWrite(led1, LOW);
digitalWrite(led3, LOW);
digitalWrite(led6, LOW);
digitalWrite(led8, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led9, HIGH);
delay(100);
digitalWrite(led2, LOW);
digitalWrite(led4, LOW);
digitalWrite(led7, LOW);
digitalWrite(led9, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led0, HIGH);
delay(100);
digitalWrite(led3, LOW);
digitalWrite(led5, LOW);
digitalWrite(led8, LOW);
digitalWrite(led0, LOW);
digitalWrite(led4, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led9, HIGH);
digitalWrite(led1, HIGH);
delay(100);
digitalWrite(led4, LOW);
digitalWrite(led6, LOW);
digitalWrite(led9, LOW);
digitalWrite(led1, LOW);
digitalWrite(led5, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led0, HIGH);
digitalWrite(led2, HIGH);
delay(100);
digitalWrite(led5, LOW);
digitalWrite(led7, LOW);
digitalWrite(led0, LOW);
digitalWrite(led2, LOW);
digitalWrite(led6, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led3, HIGH);
delay(100);
digitalWrite(led6, LOW);
digitalWrite(led8, LOW);
digitalWrite(led1, LOW);
digitalWrite(led3, LOW);
digitalWrite(led7, HIGH);
digitalWrite(led9, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led4, HIGH);
delay(100);
digitalWrite(led7, LOW);
digitalWrite(led9, LOW);
digitalWrite(led2, LOW);
digitalWrite(led4, LOW);
digitalWrite(led8, HIGH);
digitalWrite(led0, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led5, HIGH);
delay(100);
digitalWrite(led8, LOW);
digitalWrite(led0, LOW);
digitalWrite(led3, LOW);
digitalWrite(led5, LOW);
digitalWrite(led9, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led6, HIGH);
delay(100);
digitalWrite(led9, LOW);
digitalWrite(led1, LOW);
digitalWrite(led4, LOW);
digitalWrite(led6, LOW);
}

// EFEITO 15 - Começa nos cantos ********************************
for(int i = 0; i < 4; i++){
digitalWrite(led0, HIGH);
delay(182);
digitalWrite(led9, HIGH);
delay(182);
digitalWrite(led1, HIGH);
delay(182);
digitalWrite(led8, HIGH);
delay(182);
digitalWrite(led2, HIGH);
delay(182);
digitalWrite(led7, HIGH);
delay(182);
digitalWrite(led3, HIGH);
delay(182);
digitalWrite(led6, HIGH);
delay(182);
digitalWrite(led4, HIGH);
delay(182);
digitalWrite(led5, HIGH);
delay(182);
digitalWrite(led0, LOW);
delay(182);
digitalWrite(led9, LOW);
delay(182);
digitalWrite(led1, LOW);
delay(182);
digitalWrite(led8, LOW);
delay(182);
digitalWrite(led2, LOW);
delay(182);
digitalWrite(led7, LOW);
delay(182);
digitalWrite(led3, LOW);
delay(182);
digitalWrite(led6, LOW);
delay(182);
digitalWrite(led4, LOW);
delay(182);
digitalWrite(led5, LOW);
delay(182);
}

// EFEITO 16 - 2 em 2 Apagados ********************************
for(int i = 0; i < 4; i++){
digitalWrite(led0, LOW);
digitalWrite(led1, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(125);

digitalWrite(led0, HIGH);
digitalWrite(led2, LOW);
delay(125);
digitalWrite(led1, HIGH);
digitalWrite(led3, LOW);
delay(125);
digitalWrite(led2, HIGH);
digitalWrite(led4, LOW);
delay(125);
digitalWrite(led3, HIGH);
digitalWrite(led5, LOW);
delay(125);
digitalWrite(led4, HIGH);
digitalWrite(led6, LOW);
delay(125);
digitalWrite(led5, HIGH);
digitalWrite(led7, LOW);
delay(125);
digitalWrite(led6, HIGH);
digitalWrite(led8, LOW);
delay(125);
digitalWrite(led7, HIGH);
digitalWrite(led9, LOW);
delay(125);
digitalWrite(led9, HIGH);
digitalWrite(led7, LOW);
delay(125);
digitalWrite(led8, HIGH);
digitalWrite(led6, LOW);
delay(125);
digitalWrite(led7, HIGH);
digitalWrite(led5, LOW);
delay(125);
digitalWrite(led6, HIGH);
digitalWrite(led4, LOW);
delay(125);
digitalWrite(led5, HIGH);
digitalWrite(led3, LOW);
delay(125);
digitalWrite(led4, HIGH);
digitalWrite(led2, LOW);
delay(125);
digitalWrite(led3, HIGH);
digitalWrite(led1, LOW);
delay(125);
}

// EFEITO 17- Aleatorio ********************************
for(int i = 0; i < 30; i++){
digitalWrite(led2, HIGH);
delay(25);
digitalWrite(led2, LOW);
delay(25);
digitalWrite(led0, HIGH);
delay(25);
digitalWrite(led0, LOW);
delay(25);
digitalWrite(led3, HIGH);
delay(25);
digitalWrite(led3, LOW);
delay(25);
digitalWrite(led7, HIGH);
delay(25);
digitalWrite(led7, LOW);
delay(25);
digitalWrite(led1, HIGH);
delay(25);
digitalWrite(led1, LOW);
delay(25);
digitalWrite(led8, HIGH);
delay(25);
digitalWrite(led8, LOW);
delay(25);
digitalWrite(led5, HIGH);
delay(25);
digitalWrite(led5, LOW);
delay(25);
digitalWrite(led9, HIGH);
delay(25);
digitalWrite(led9, LOW);
delay(25);
digitalWrite(led4, HIGH);
delay(25);
digitalWrite(led4, LOW);
delay(25);
digitalWrite(led6, HIGH);
delay(25);
digitalWrite(led6, LOW);
delay(25);
}

// EFEITO 18- ********************************
for(int i = 0; i < 6; i++){
digitalWrite(led0, HIGH);
delay(85);
digitalWrite(led1, HIGH);
delay(85);
digitalWrite(led2, HIGH);
delay(85);
digitalWrite(led3, HIGH);
delay(85);
digitalWrite(led4, HIGH);
delay(85);
digitalWrite(led5, HIGH);
delay(85);
digitalWrite(led6, HIGH);
delay(85);
digitalWrite(led7, HIGH);
delay(85);
digitalWrite(led8, HIGH);
delay(85);
digitalWrite(led9, HIGH);
delay(85);
digitalWrite(led9, LOW);
digitalWrite(led8, LOW);
digitalWrite(led7, LOW);
digitalWrite(led6, LOW);
digitalWrite(led5, LOW);
digitalWrite(led4, LOW);
digitalWrite(led3, LOW);
digitalWrite(led2, LOW);
digitalWrite(led1, LOW);
digitalWrite(led0, LOW);
delay(85);
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(85);
digitalWrite(led9, LOW);
digitalWrite(led8, LOW);
digitalWrite(led7, LOW);
digitalWrite(led6, LOW);
digitalWrite(led5, LOW);
digitalWrite(led4, LOW);
digitalWrite(led3, LOW);
digitalWrite(led2, LOW);
digitalWrite(led1, LOW);
digitalWrite(led0, LOW);
delay(85);
digitalWrite(led9, HIGH);
delay(85);
digitalWrite(led8, HIGH);
delay(85);
digitalWrite(led7, HIGH);
delay(85);
digitalWrite(led6, HIGH);
delay(85);
digitalWrite(led5, HIGH);
delay(85);
digitalWrite(led4, HIGH);
delay(85);
digitalWrite(led3, HIGH);
delay(85);
digitalWrite(led2, HIGH);
delay(85);
digitalWrite(led1, HIGH);
delay(85);
digitalWrite(led0, HIGH);
delay(85);
digitalWrite(led9, LOW);
digitalWrite(led8, LOW);
digitalWrite(led7, LOW);
digitalWrite(led6, LOW);
digitalWrite(led5, LOW);
digitalWrite(led4, LOW);
digitalWrite(led3, LOW);
digitalWrite(led2, LOW);
digitalWrite(led1, LOW);
digitalWrite(led0, LOW);
delay(85);
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(85);
digitalWrite(led9, LOW);
digitalWrite(led8, LOW);
digitalWrite(led7, LOW);
digitalWrite(led6, LOW);
digitalWrite(led5, LOW);
digitalWrite(led4, LOW);
digitalWrite(led3, LOW);
digitalWrite(led2, LOW);
digitalWrite(led1, LOW);
digitalWrite(led0, LOW);
delay(85);
}

// EFEITO 19- ********************************
for(int i = 0; i < 6; i++){
digitalWrite(led0, HIGH);
digitalWrite(led5, HIGH);
delay(200);
digitalWrite(led1, HIGH);
digitalWrite(led6, HIGH);
delay(200);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(200);
digitalWrite(led3, HIGH);
digitalWrite(led8, HIGH);
delay(200);
digitalWrite(led4, HIGH);
digitalWrite(led9, HIGH);
delay(200);
digitalWrite(led0, LOW);
digitalWrite(led5, LOW);
delay(200);
digitalWrite(led1, LOW);
digitalWrite(led6, LOW);
delay(200);
digitalWrite(led2, LOW);
digitalWrite(led7, LOW);
delay(200);
digitalWrite(led3, LOW);
digitalWrite(led8, LOW);
delay(200);
digitalWrite(led4, LOW);
digitalWrite(led9, LOW);
delay(200);
}

// EFEITO 20- ********************************
for(int i = 0; i < 5; i++){
digitalWrite(led0, LOW);
digitalWrite(led1, LOW);
digitalWrite(led2, LOW);
digitalWrite(led3, LOW);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led6, LOW);
digitalWrite(led7, LOW);
digitalWrite(led8, LOW);
digitalWrite(led9, LOW);
delay(350);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
delay(350);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
delay(350);
digitalWrite(led3, LOW);
digitalWrite(led6, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(350);
digitalWrite(led2, LOW);
digitalWrite(led7, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led8, HIGH);
delay(350);
digitalWrite(led1, LOW);
digitalWrite(led8, LOW);
digitalWrite(led0, HIGH);
digitalWrite(led9, HIGH);
delay(350);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
delay(350);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
delay(350);
digitalWrite(led3, LOW);
digitalWrite(led6, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(350);
digitalWrite(led2, LOW);
digitalWrite(led7, LOW);
digitalWrite(led1, HIGH);
digitalWrite(led8, HIGH);
delay(350);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
delay(350);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
delay(350);
digitalWrite(led3, LOW);
digitalWrite(led6, LOW);
digitalWrite(led2, HIGH);
digitalWrite(led7, HIGH);
delay(350);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
delay(350);
digitalWrite(led4, LOW);
digitalWrite(led5, LOW);
digitalWrite(led3, HIGH);
digitalWrite(led6, HIGH);
delay(350);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
delay(350);
}

// EFEITO 21- ********************************
for(int i = 0; i < 8; i++){
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(120);
digitalWrite(led9, LOW);
digitalWrite(led8, LOW);
digitalWrite(led7, LOW);
digitalWrite(led6, LOW);
digitalWrite(led5, LOW);
digitalWrite(led4, LOW);
digitalWrite(led3, LOW);
digitalWrite(led2, LOW);
digitalWrite(led1, LOW);
digitalWrite(led0, LOW);
delay(120);
digitalWrite(led0, HIGH);
digitalWrite(led1, HIGH);
digitalWrite(led2, HIGH);
digitalWrite(led3, HIGH);
digitalWrite(led4, HIGH);
digitalWrite(led5, HIGH);
digitalWrite(led6, HIGH);
digitalWrite(led7, HIGH);
digitalWrite(led8, HIGH);
digitalWrite(led9, HIGH);
delay(120);
digitalWrite(led9, LOW);
digitalWrite(led8, LOW);
digitalWrite(led7, LOW);
digitalWrite(led6, LOW);
digitalWrite(led5, LOW);
digitalWrite(led4, LOW);
digitalWrite(led3, LOW);
digitalWrite(led2, LOW);
digitalWrite(led1, LOW);
digitalWrite(led0, LOW);
delay(400);
}

// EFEITO 22- ********************************
for(int i = 0; i < 5; i++){
//Indo
digitalWrite(led0, HIGH);
delay(150);
digitalWrite(led1, HIGH);
delay(150);
digitalWrite(led2, HIGH);
delay(150);
digitalWrite(led0, LOW);
digitalWrite(led3, HIGH);
delay(150);
digitalWrite(led1, LOW);
digitalWrite(led4, HIGH);
delay(150);
digitalWrite(led2, LOW);
digitalWrite(led5, HIGH);
delay(150);
digitalWrite(led3, LOW);
digitalWrite(led6, HIGH);
delay(150);
digitalWrite(led4, LOW);
digitalWrite(led7, HIGH);
delay(150);
digitalWrite(led5, LOW);
digitalWrite(led8, HIGH);
delay(150);
digitalWrite(led6, LOW);
digitalWrite(led9, HIGH);
delay(150);
digitalWrite(led7, LOW);
delay(150);
digitalWrite(led8, LOW);
delay(150);
digitalWrite(led9, LOW);
delay(150);
//Voltando
digitalWrite(led9, HIGH);
delay(150);
digitalWrite(led8, HIGH);
delay(150);
digitalWrite(led7, HIGH);
delay(150);
digitalWrite(led9, LOW);
digitalWrite(led6, HIGH);
delay(150);
digitalWrite(led8, LOW);
digitalWrite(led5, HIGH);
delay(150);
digitalWrite(led7, LOW);
digitalWrite(led4, HIGH);
delay(150);
digitalWrite(led6, LOW);
digitalWrite(led3, HIGH);
delay(150);
digitalWrite(led5, LOW);
digitalWrite(led2, HIGH);
delay(150);
digitalWrite(led4, LOW);
digitalWrite(led1, HIGH);
delay(150);
digitalWrite(led3, LOW);
digitalWrite(led0, HIGH);
delay(150);
digitalWrite(led2, LOW);
delay(150);
digitalWrite(led1, LOW);
delay(150);
digitalWrite(led0, LOW);
delay(150);
}
}

